### ISSUE TITLE
KeyError: 'access_token' -> check for auth errors

### ISSUE THREAD

**Issue by rogersmj** [zpriddy/SmartThings_PyDash#1]
When I run this, after authorization with SmartThings I'm getting the following error:

```
Traceback (most recent call last):
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mrogers/.virtualenvs/pydash/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mrogers/Projects/SmartThings_PyDash/ZP_PyDash/main.py", line 40, in init
    zp_st.init()
  File "/Users/mrogers/Projects/SmartThings_PyDash/ZP_PyDash/zp_pydashie_interface.py", line 108, in init
    smartThings.request_endpoints()
  File "/Users/mrogers/Projects/SmartThings_PyDash/ZP_PyDash/zp_smartthings.py", line 76, in request_endpoints
    "access_token": self.std["access_token"]
KeyError: 'access_token'
```

It seems that there's no access token available? I'm still troubleshooting but thought I'd see if anyone has any ideas.

(FYI I'm running this using a virtual environment wrapper)

**Comment by rogersmj** [comment]
Of course, as soon as I post this I figure it out... I had updated by oauth secret but not hit "Save" on the SmartThings IDE when I did so. Thus, PyDash was failing to authorize.

Auth failure might be a good thing to handle a little more gracefully, though.

**Comment by zpriddy** [comment]
I will have to look back into doing that... I originally had better checking and error handling...  but I had a side effect that each time you would load the page or refresh the page it would start a new threading process of checking smartthings... this resulted in me trying to figure out how i got 600 API requests in under 10 seconds... So I had to revert it..
